name: stock_learn
description: "for students"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  qr_code_scanner: ^1.0.1
  modal_bottom_sheet: ^3.0.0
  flutter_svg: ^2.0.10+1
  riverpod: ^2.5.1
  animations: ^2.0.11
  freezed: ^2.5.2
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Pretendard
      fonts:
        - asset: Pretendard-Bold.ttf
          weight: 700
        - asset: Pretendard-SemiBold.ttf
          weight: 600
        - asset: Pretendard-Regular.ttf
          weight: 400